#!/usr/bin/env sh

echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
echo 'PermitEmptyPasswords yes' >> /etc/ssh/sshd_config
passwd -d root

mount -t tmpfs none /tmp
udhcpc

rm '/usr/lib/systemd/system/serial-getty@.service'
exec /usr/bin/systemd
