#!/usr/bin/env bash

set -e

# A bridge of this name will be created to host the TAP interface created for
# the VM
QEMU_BRIDGE='qemubr0'

# DHCPD must have an IP address to run, but that address doesn't have to
# be valid. This is the dummy address dhcpd is configured to use.
DUMMY_DHCPD_IP='10.0.0.1'

# These scripts configure/deconfigure the VM interface on the bridge.
QEMU_IFUP='/boot/qemu-ifup'
QEMU_IFDOWN='/boot/qemu-ifdown'

# The name of the dhcpd config file we make
DHCPD_CONF_FILE='/boot/dhcpd.conf'

function default_intf() {
    ip -json route show |
        jq -r '.[] | select(.dst == "default") | .dev'
}

# First step, we run the things that need to happen before we start mucking
# with the interfaces. We start by generating the DHCPD config file based
# on our current address/routes. We "steal" the container's IP, and lease
# it to the VM once it starts up.
/boot/generate-dhcpd-conf $QEMU_BRIDGE > $DHCPD_CONF_FILE
default_dev=`default_intf`

# Now we start modifying the networking configuration. First we clear out
# the IP address of the default device (will also have the side-effect of
# removing the default route)
ip addr flush dev $default_dev

# Next, we create our bridge, and add our container interface to it.
ip link add $QEMU_BRIDGE type bridge
ip link set dev $default_dev master $QEMU_BRIDGE

# Then, we toggle the interface and the bridge to make sure everything is up
# and running.
ip link set dev $default_dev up
ip link set dev $QEMU_BRIDGE up

# Finally, start our DHCPD server
touch /var/lib/misc/udhcpd.leases
udhcpd -I $DUMMY_DHCPD_IP -f $DHCPD_CONF_FILE &

KVM=$([ -e /dev/kvm ] && echo '-enable-kvm' || echo '')

exec /usr/bin/qemu-system-x86_64 \
     $KVM \
     -smp 4 \
     -m 8G \
     -kernel /boot/bzImage \
     -fsdev local,id=root,path=/,security_model=passthrough,writeout=immediate \
     -device virtio-9p-pci,fsdev=root,mount_tag=/dev/root \
     -nic tap,id=qemu0,script=$QEMU_IFUP,downscript=$QEMU_IFDOWN \
     -nographic \
     -monitor none \
     -append "root=/dev/root rw rootfstype=9p rootflags=trans=virtio console=ttyS0 init=/boot/init"
